# Generated by Django 3.2 on 2021-04-10 15:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('maxGuests', models.PositiveSmallIntegerField()),
                ('is_cancelled', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('vegetarian', 'vegetarian'), ('vegan', 'vegan'), ('no_egg', 'no_egg'), ('gluten_free', 'gluten_free'), ('lactose_free', 'lactose_free'), ('no_nut', 'no_nut')], max_length=50)),
                ('dinner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='dinnerEvent.dinnerevent')),
            ],
        ),
    ]
